#!/usr/bin/env python3
"""
Convert OpenSeeker-v1-Data to the standardized chat format.

OpenSeeker (PolarSeeker/OpenSeeker-v1-Data) is an agentic web-search QA dataset
(constraint-satisfaction questions) generated by Qwen3-30B-A3B-Thinking. Columns:

  question                : the user task (str)
  answer                  : gold short answer (str)
  number of tool calls    : int
  trajectory              : list[{role, content}] - the full agent run
  trajectory correctness  : "Correct" | "Incorrect"

Only **Correct** trajectories are kept (SFT shouldn't learn from runs that reached
the wrong answer). Decontamination is skipped (treated as OOD agentic, per the
Toucan decision).

The `trajectory` is a Qwen3/Hermes-style chat where everything agentic is inline
XML markup inside the `content` strings:
  * trajectory[0] (system): a QA-agent instruction, then "# Tools" with function
    signatures inside <tools>{json}\n{json}</tools>. NOTE the instruction text also
    contains a literal empty "<tools></tools>" - we take the non-empty block.
  * trajectory[1] (user): the question.
  * assistant turns: <think>...</think> reasoning, then tool calls wrapped in
    <tool_calls_begin>/<tool_call>{"name","arguments"}</tool_call>/</tool_calls_end>.
  * tool outputs come back as **user** messages wrapped in <tool_response>...</tool_response>.
  * final assistant turn: <think>...</think> then the answer in <answer>...</answer>.

Mapping to the unified parts schema:
  * system_prompt   = the cleaned QA-agent instruction (text before "# Tools");
                      tools go to available_functions, NOT into the system prompt.
  * available_functions = the <tools> defs (parameters serialized to a JSON string).
  * initial_prompt  = the first user message (the question).
  * The whole rest of the trajectory collapses into ONE assistant message whose parts
    are: thought / function-call / function-output / response. Tool outputs (which live
    in the following user/<tool_response> message) are folded back in, and parallel
    calls are interleaved with their outputs ([call_1, out_1, call_2, out_2, ...]) so
    that 07-dataset-aggregation/linearise-dataset.py does not break on
    [call, call, output, output].

Example:
  .venv/bin/python 02-standardisation/convert-openseeker.py \\
    data/01-hf-data/OpenSeeker-v1-Data -o data/02-standardised/
"""

import sys
import re
import json
import argparse
import hashlib
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional, Tuple

from tqdm import tqdm
from datasets import load_from_disk, DatasetDict, Dataset

DATASET_SOURCE = "OpenSeeker-v1-Data"

_THINK_RE = re.compile(r"<think>(.*?)</think>", re.DOTALL)
_TOOLCALL_RE = re.compile(r"<tool_call>\s*(.*?)\s*</tool_call>", re.DOTALL)
_TOOLRESP_RE = re.compile(r"<tool_response>(.*?)</tool_response>", re.DOTALL)
_TOOLS_RE = re.compile(r"<tools>(.*?)</tools>", re.DOTALL)
_TC_WRAPPER_RE = re.compile(r"</?tool_calls_(?:begin|end)>")


def generate_conversation_id(dataset_source: str, seed: str) -> str:
    """Generate a unique conversation ID (sha256[:12] of a stable seed)."""
    content_hash = hashlib.sha256(seed.encode("utf-8")).hexdigest()[:12]
    prefix = dataset_source.replace("/", "_").replace("-", "_")
    return f"{prefix}_{content_hash}"


def create_unified_part(
    part_type: str,
    content: str = "",
    name: str = "",
    args: str = "",
    metadata: Optional[Dict] = None,
) -> Dict[str, Any]:
    """Unified part with all fields, for Arrow schema consistency (matches convert-toucan)."""
    return {
        "type": part_type,
        "content": content,
        "metadata": metadata or {},
        "name": name,
        "args": args,
        "answers": [],
    }


def parse_system(content: str) -> Tuple[str, List[Dict[str, Any]]]:
    """Return (cleaned_system_prompt, available_functions) from the system message."""
    system_prompt = content.split("# Tools")[0].strip()

    available_functions: List[Dict[str, Any]] = []
    # The instruction text contains a literal empty "<tools></tools>"; take the
    # non-empty block (the real definitions).
    blocks = [b for b in _TOOLS_RE.findall(content) if b.strip()]
    if blocks:
        blob = max(blocks, key=len)
        for line in blob.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                fn = json.loads(line)
            except json.JSONDecodeError:
                continue
            name = (fn.get("name") or "").strip()
            if not name:
                continue
            params = fn.get(
                "parameters", {"type": "object", "properties": {}, "required": []}
            )
            available_functions.append(
                {
                    "name": name,
                    "description": fn.get("description", "") or "",
                    "parameters": json.dumps(params),
                }
            )
    return system_prompt, available_functions


def parse_tool_calls(assistant_content: str) -> List[Tuple[str, str]]:
    """Extract (name, args_json_string) for each <tool_call> in an assistant turn."""
    calls = []
    for payload in _TOOLCALL_RE.findall(assistant_content):
        try:
            obj = json.loads(payload)
        except json.JSONDecodeError:
            continue
        if not isinstance(obj, dict):
            continue
        name = (obj.get("name") or "").strip()
        if not name:
            continue
        args = obj.get("arguments", "")
        if isinstance(args, str):
            pass
        elif args is None:
            args = ""
        else:
            try:
                args = json.dumps(args)
            except (TypeError, ValueError):
                args = ""
        calls.append((name, args))
    return calls


def extract_response_text(assistant_content: str) -> str:
    """Leftover assistant text after removing <think>, tool-call markup, and <answer> tags."""
    text = _THINK_RE.sub("", assistant_content)
    text = _TOOLCALL_RE.sub("", text)
    text = _TC_WRAPPER_RE.sub("", text)
    text = text.replace("<answer>", "").replace("</answer>", "")
    return text.strip()


def convert_sample(row: Dict[str, Any], idx: int) -> Tuple[Optional[Dict[str, Any]], bool]:
    """Convert one Correct OpenSeeker row to the unified chat format. Returns (sample, anomaly)."""
    traj = row.get("trajectory") or []
    if not isinstance(traj, list) or len(traj) < 3:
        return None, False
    if traj[0].get("role") != "system" or traj[1].get("role") != "user":
        return None, False

    system_prompt, available_functions = parse_system(traj[0].get("content", ""))
    initial_prompt_content = traj[1].get("content", "") or ""

    parts: List[Dict[str, Any]] = []
    had_anomaly = False

    # Pair each assistant turn's tool calls with the immediately-following
    # user/<tool_response> message (round-scoped). OpenSeeker sometimes emits more
    # parallel calls than the environment returns responses for; we pair the first-N
    # (response order matches call order) and drop the unanswered extra calls, so
    # nothing is mis-paired across rounds and linearise never sees a dangling call.
    items = traj[2:]
    n = len(items)
    i = 0
    while i < n:
        item = items[i]
        role = item.get("role", "")
        content = item.get("content", "") or ""

        if role == "assistant":
            think = _THINK_RE.search(content)
            if think and think.group(1).strip():
                parts.append(create_unified_part("thought", content=think.group(1).strip()))

            calls = parse_tool_calls(content)
            if calls:
                outputs: List[str] = []
                if i + 1 < n and items[i + 1].get("role") == "user":
                    outputs = [
                        o.strip()
                        for o in _TOOLRESP_RE.findall(items[i + 1].get("content", "") or "")
                    ]
                    if outputs:
                        i += 1  # consume the tool-response message paired with this turn
                k = min(len(calls), len(outputs))
                for j in range(k):
                    parts.append(create_unified_part("function-call", name=calls[j][0], args=calls[j][1]))
                    parts.append(create_unified_part("function-output", content=outputs[j]))
                if len(calls) != len(outputs):
                    had_anomaly = True  # dropped unanswered extra calls (or extra outputs)

            response_text = extract_response_text(content)
            if response_text:
                parts.append(create_unified_part("response", content=response_text))

        elif role == "user":
            # A user message not consumed above: an orphan tool_response or a genuine
            # follow-up turn. Neither occurs in well-formed OpenSeeker; flag it.
            had_anomaly = True

        i += 1

    if not parts:
        return None, had_anomaly

    sample = {
        "conversation_id": generate_conversation_id(DATASET_SOURCE, f"{idx}_{initial_prompt_content}"),
        "dataset_source": DATASET_SOURCE,
        "original_metadata": {
            "answer": row.get("answer", "") or "",
            "trajectory_correctness": row.get("trajectory correctness", "") or "",
            "number_of_tool_calls": int(row.get("number of tool calls", 0) or 0),
            "row_index": idx,
        },
        "system_prompt": {"content": system_prompt, "metadata": {}},
        "initial_prompt": {"role": "user", "content": initial_prompt_content, "metadata": {}},
        "available_functions": available_functions,
        "conversation_branches": [{"messages": [{"role": "assistant", "parts": parts, "metadata": {}}]}],
        "created_timestamp": datetime.now().isoformat(),
    }
    return sample, had_anomaly


def process_dataset(dataset: Dataset, chunk_size: int = 1000) -> Dataset:
    """Keep only Correct trajectories, then convert to the unified chat format."""
    before = len(dataset)
    dataset = dataset.filter(
        lambda r: r["trajectory correctness"] == "Correct", desc="Keep Correct only"
    )
    print(f"Correctness filter: kept {len(dataset):,} / {before:,} (Correct only)")

    total = len(dataset)
    converted: List[Dict[str, Any]] = []
    failed = anomalies = 0

    with tqdm(total=total, desc="Converting OpenSeeker", unit="samples") as pbar:
        for start in range(0, total, chunk_size):
            for idx in range(start, min(start + chunk_size, total)):
                sample, anomaly = convert_sample(dataset[idx], idx)
                if sample is not None:
                    converted.append(sample)
                    anomalies += int(anomaly)
                else:
                    failed += 1
                pbar.update(1)
                pbar.set_postfix(failed=failed, anomalies=anomalies)

    print(f"Conversion complete: {len(converted):,} converted, {failed:,} skipped, {anomalies:,} anomalies")
    return Dataset.from_list(converted) if converted else Dataset.from_list([])


def save_dataset_and_metadata(dataset_dict: DatasetDict, output_path: Path, input_path: Path):
    output_path.mkdir(parents=True, exist_ok=True)
    dataset_dict.save_to_disk(str(output_path))
    metadata = {
        "processing_log": [
            {
                "operation": "convert_openseeker",
                "script": "convert-openseeker.py",
                "timestamp": datetime.now().isoformat(),
                "input_path": str(input_path),
                "output_path": str(output_path),
                "description": (
                    "Converted OpenSeeker-v1-Data to the unified chat format. Kept Correct "
                    "trajectories only; parsed Qwen3 inline markup (<think>/<tool_call>/"
                    "<tool_response>/<answer>); carried the cleaned QA-agent system prompt; "
                    "tools -> available_functions; parallel calls interleaved with outputs."
                ),
            }
        ],
        "format": "chat_format_v1_new",
        "source_dataset": DATASET_SOURCE,
        "conversion_details": {
            "function_format": "openai_compatible",
            "conversation_type": "multi_turn_agentic_tool_use_with_thinking",
            "parts_structure": "unified_schema",
            "kept": "trajectory_correctness == Correct",
            "special_features": ["multi_turn", "thinking", "function_calling", "parallel_call_interleaving"],
        },
    }
    with open(output_path / "dataset_metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"Dataset saved to {output_path}")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert OpenSeeker-v1-Data to the standardized chat format",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Example:\n"
            "  .venv/bin/python 02-standardisation/convert-openseeker.py \\\n"
            "    data/01-hf-data/OpenSeeker-v1-Data -o data/02-standardised/\n"
        ),
    )
    parser.add_argument("input_path", type=str, help="Path to OpenSeeker dataset (load_from_disk format)")
    parser.add_argument("-o", "--output", type=str, required=True, help="Output directory")
    parser.add_argument("--batch-size", type=int, default=1000, help="Chunk size (default: 1000)")
    parser.add_argument("--sample", type=int, default=None, help="Only convert first N rows (testing)")
    return parser.parse_args()


def main() -> None:
    args = parse_arguments()
    input_path = Path(args.input_path)
    if not input_path.exists():
        print(f"Error: input path does not exist: {input_path}")
        sys.exit(1)

    output_path = Path(args.output)
    if args.output.endswith("/") or (output_path.exists() and output_path.is_dir()):
        output_path = output_path / input_path.name

    print(f"Input:  {input_path}\nOutput: {output_path}")
    dataset = load_from_disk(str(input_path))
    if not isinstance(dataset, DatasetDict):
        dataset = DatasetDict({"train": dataset})

    processed = {}
    for split_name, split in dataset.items():
        if args.sample:
            split = split.select(range(min(args.sample, len(split))))
            print(f"Sampling first {len(split):,} of '{split_name}'")
        print(f"Processing '{split_name}': {len(split):,} samples")
        processed[split_name] = process_dataset(split, chunk_size=args.batch_size)

    processed_dataset = DatasetDict(processed)
    save_dataset_and_metadata(processed_dataset, output_path, input_path)
    total = sum(len(s) for s in processed_dataset.values())
    print(f"\nDone. Total samples: {total:,}")
    if "train" in processed_dataset:
        print(f"Features: {list(processed_dataset['train'].features.keys())}")


if __name__ == "__main__":
    main()
