#!/usr/bin/env python3
"""
Convert EnvScaler-SFT-Traj-9K to the standardized chat format.

EnvScaler (XXHStudyHard/EnvScaler-SFT-Traj-9K) is a text-only agentic multi-turn
tool-use dataset generated by Qwen3-30B-A3B-Thinking via programmatic environment
synthesis. We use the `envscaler_sft_traj_9k_metadata.json` file (the repo also ships a
pre-templated LLaMA-Factory file, which breaks `load_dataset`; stage 01 targets only the
metadata file). Columns: traj_type, task_info(dict), tools(JSON str), messages(JSON str),
user_messages(JSON str), steps(int).

`messages` is **clean OpenAI chat** (no inline markup):
  * system            -> the agentic instruction
  * user              -> genuine user-simulator turns (multiple, interleaved with tools)
  * assistant         -> { reasoning_content (the <think> equivalent), content (text),
                           tool_calls ([{type:function, function:{name, arguments}}]) }
  * tool              -> tool output (one message per call; no tool_call_id, matched by order)

Mapping to the unified parts schema:
  * system_prompt   = the system message (carried; house convention is carry-if-present).
  * available_functions = `tools` (OpenAI defs; parameters serialized to a JSON string).
  * initial_prompt  = the first user message.
  * Each assistant turn -> thought (reasoning_content) / function-call (tool_calls) /
    response (content). Tool outputs (the following `tool` messages) are folded in and
    paired round-scoped with the calls of the immediately-preceding assistant turn
    (first-N, drop unanswered extras) so linearise never sees a dangling call. Genuine
    `user` turns split assistant messages.

Example:
  .venv/bin/python 02-standardisation/convert-envscaler.py \\
    data/01-hf-data/EnvScaler-SFT-Traj-9K -o data/02-standardised/
"""

import sys
import json
import argparse
import hashlib
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional, Tuple

from tqdm import tqdm
from datasets import load_from_disk, DatasetDict, Dataset

DATASET_SOURCE = "EnvScaler-SFT-Traj-9K"


def generate_conversation_id(dataset_source: str, seed: str) -> str:
    content_hash = hashlib.sha256(seed.encode("utf-8")).hexdigest()[:12]
    prefix = dataset_source.replace("/", "_").replace("-", "_")
    return f"{prefix}_{content_hash}"


def create_unified_part(
    part_type: str,
    content: str = "",
    name: str = "",
    args: str = "",
    metadata: Optional[Dict] = None,
) -> Dict[str, Any]:
    """Unified part with all fields, for Arrow schema consistency (matches sibling converters)."""
    return {
        "type": part_type,
        "content": content,
        "metadata": metadata or {},
        "name": name,
        "args": args,
        "answers": [],
    }


def convert_tools(tools_json_str: str) -> List[Dict[str, Any]]:
    """Convert the OpenAI `tools` list to available_functions (parameters -> JSON string)."""
    try:
        tools = json.loads(tools_json_str)
    except (json.JSONDecodeError, TypeError):
        return []
    if not isinstance(tools, list):
        return []
    out = []
    for t in tools:
        if not isinstance(t, dict):
            continue
        fn = t.get("function", t)
        if not isinstance(fn, dict):
            continue
        name = (fn.get("name") or "").strip()
        if not name:
            continue
        params = fn.get("parameters", {"type": "object", "properties": {}, "required": []})
        out.append(
            {
                "name": name,
                "description": fn.get("description", "") or "",
                "parameters": json.dumps(params),
            }
        )
    return out


def extract_tool_call(tc: Dict[str, Any]) -> Tuple[str, str]:
    """Return (name, args_json_string) from an OpenAI tool_call object."""
    if not isinstance(tc, dict):
        return "", ""
    fn = tc.get("function", tc)
    if not isinstance(fn, dict):
        return "", ""
    name = (fn.get("name") or "").strip()
    args = fn.get("arguments", "")
    if isinstance(args, str):
        pass
    elif args is None:
        args = ""
    else:
        try:
            args = json.dumps(args)
        except (TypeError, ValueError):
            args = ""
    return name, args


def parse_task_info(ti: Any) -> Dict[str, Any]:
    if isinstance(ti, str):
        try:
            ti = json.loads(ti)
        except json.JSONDecodeError:
            return {}
    return ti if isinstance(ti, dict) else {}


def convert_sample(row: Dict[str, Any], idx: int) -> Tuple[Optional[Dict[str, Any]], bool]:
    try:
        msgs = json.loads(row["messages"])
    except (json.JSONDecodeError, TypeError, KeyError):
        return None, False
    if not isinstance(msgs, list) or not msgs:
        return None, False

    system_content = ""
    if msgs[0].get("role") == "system":
        system_content = msgs[0].get("content", "") or ""

    first_user_idx = next((i for i, m in enumerate(msgs) if m.get("role") == "user"), None)
    if first_user_idx is None:
        return None, False
    initial_prompt_content = msgs[first_user_idx].get("content", "") or ""

    items = msgs[first_user_idx + 1:]
    n = len(items)
    conv_messages: List[Dict[str, Any]] = []
    parts: List[Dict[str, Any]] = []
    had_anomaly = False
    i = 0
    while i < n:
        m = items[i]
        role = m.get("role", "")

        if role == "user":
            if parts:
                conv_messages.append({"role": "assistant", "parts": parts, "metadata": {}})
                parts = []
            conv_messages.append(
                {
                    "role": "user",
                    "parts": [create_unified_part("response", content=m.get("content", "") or "")],
                    "metadata": {},
                }
            )
            i += 1

        elif role == "assistant":
            rc = m.get("reasoning_content")
            if rc and rc.strip():
                parts.append(create_unified_part("thought", content=rc.strip()))

            tcs = m.get("tool_calls") or []
            if tcs:
                # Outputs are the consecutive `tool` messages right after this turn.
                outputs: List[str] = []
                j = i + 1
                while j < n and items[j].get("role") == "tool":
                    outputs.append(items[j].get("content", "") or "")
                    j += 1
                k = min(len(tcs), len(outputs))
                for x in range(k):
                    name, args = extract_tool_call(tcs[x])
                    if not name:
                        had_anomaly = True
                        continue
                    parts.append(create_unified_part("function-call", name=name, args=args))
                    parts.append(create_unified_part("function-output", content=outputs[x]))
                if len(tcs) != len(outputs):
                    had_anomaly = True  # dropped unanswered extra calls (or extra outputs)
                i = j
            else:
                i += 1

            content = m.get("content")
            if content and content.strip():
                parts.append(create_unified_part("response", content=content.strip()))

        elif role == "tool":
            # tool output not consumed by a preceding assistant turn -> orphan; flag.
            had_anomaly = True
            i += 1
        else:
            i += 1

    if parts:
        conv_messages.append({"role": "assistant", "parts": parts, "metadata": {}})

    if not conv_messages:
        return None, had_anomaly

    ti = parse_task_info(row.get("task_info"))
    sample = {
        "conversation_id": generate_conversation_id(
            DATASET_SOURCE, f"{idx}_{ti.get('task_id') or initial_prompt_content}"
        ),
        "dataset_source": DATASET_SOURCE,
        "original_metadata": {
            "env_id": ti.get("env_id", "") or "",
            "task_id": ti.get("task_id", "") or "",
            "traj_type": row.get("traj_type", "") or "",
            "steps": int(row.get("steps", 0) or 0),
            "row_index": idx,
        },
        "system_prompt": {"content": system_content, "metadata": {}},
        "initial_prompt": {"role": "user", "content": initial_prompt_content, "metadata": {}},
        "available_functions": convert_tools(row.get("tools", "[]")),
        "conversation_branches": [{"messages": conv_messages}],
        "created_timestamp": datetime.now().isoformat(),
    }
    return sample, had_anomaly


def process_dataset(dataset: Dataset, chunk_size: int = 1000) -> Dataset:
    total = len(dataset)
    converted: List[Dict[str, Any]] = []
    failed = anomalies = 0
    with tqdm(total=total, desc="Converting EnvScaler", unit="samples") as pbar:
        for start in range(0, total, chunk_size):
            for idx in range(start, min(start + chunk_size, total)):
                sample, anomaly = convert_sample(dataset[idx], idx)
                if sample is not None:
                    converted.append(sample)
                    anomalies += int(anomaly)
                else:
                    failed += 1
                pbar.update(1)
                pbar.set_postfix(failed=failed, anomalies=anomalies)
    print(f"Conversion complete: {len(converted):,} converted, {failed:,} skipped, {anomalies:,} anomalies")
    return Dataset.from_list(converted) if converted else Dataset.from_list([])


def save_dataset_and_metadata(dataset_dict: DatasetDict, output_path: Path, input_path: Path):
    output_path.mkdir(parents=True, exist_ok=True)
    dataset_dict.save_to_disk(str(output_path))
    metadata = {
        "processing_log": [
            {
                "operation": "convert_envscaler",
                "script": "convert-envscaler.py",
                "timestamp": datetime.now().isoformat(),
                "input_path": str(input_path),
                "output_path": str(output_path),
                "description": (
                    "Converted EnvScaler-SFT-Traj-9K (metadata file) to the unified chat format. "
                    "OpenAI messages -> parts (reasoning_content->thought, tool_calls->function-call, "
                    "tool msgs->function-output, content->response); carried the system prompt; tools -> "
                    "available_functions; round-scoped call/output pairing; genuine user turns split."
                ),
            }
        ],
        "format": "chat_format_v1_new",
        "source_dataset": DATASET_SOURCE,
        "conversion_details": {
            "function_format": "openai_compatible",
            "conversation_type": "multi_turn_agentic_tool_use_with_thinking",
            "parts_structure": "unified_schema",
            "special_features": ["multi_turn", "thinking", "function_calling", "parallel_call_interleaving"],
        },
    }
    with open(output_path / "dataset_metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"Dataset saved to {output_path}")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert EnvScaler-SFT-Traj-9K to the standardized chat format",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Example:\n"
            "  .venv/bin/python 02-standardisation/convert-envscaler.py \\\n"
            "    data/01-hf-data/EnvScaler-SFT-Traj-9K -o data/02-standardised/\n"
        ),
    )
    parser.add_argument("input_path", type=str, help="Path to EnvScaler dataset (load_from_disk format)")
    parser.add_argument("-o", "--output", type=str, required=True, help="Output directory")
    parser.add_argument("--batch-size", type=int, default=1000, help="Chunk size (default: 1000)")
    parser.add_argument("--sample", type=int, default=None, help="Only convert first N rows (testing)")
    return parser.parse_args()


def main() -> None:
    args = parse_arguments()
    input_path = Path(args.input_path)
    if not input_path.exists():
        print(f"Error: input path does not exist: {input_path}")
        sys.exit(1)

    output_path = Path(args.output)
    if args.output.endswith("/") or (output_path.exists() and output_path.is_dir()):
        output_path = output_path / input_path.name

    print(f"Input:  {input_path}\nOutput: {output_path}")
    dataset = load_from_disk(str(input_path))
    if not isinstance(dataset, DatasetDict):
        dataset = DatasetDict({"train": dataset})

    processed = {}
    for split_name, split in dataset.items():
        if args.sample:
            split = split.select(range(min(args.sample, len(split))))
            print(f"Sampling first {len(split):,} of '{split_name}'")
        print(f"Processing '{split_name}': {len(split):,} samples")
        processed[split_name] = process_dataset(split, chunk_size=args.batch_size)

    processed_dataset = DatasetDict(processed)
    save_dataset_and_metadata(processed_dataset, output_path, input_path)
    total = sum(len(s) for s in processed_dataset.values())
    print(f"\nDone. Total samples: {total:,}")
    if "train" in processed_dataset:
        print(f"Features: {list(processed_dataset['train'].features.keys())}")


if __name__ == "__main__":
    main()
